[managers]
node_a ansible_host=34.47.172.118 ansible_user=ubuntu

[workers]
node_b ansible_host=35.200.157.110 ansible_user=ubuntu

[cluster:children]
managers
workers

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
