[managers]
node_a ansible_host=34.100.232.151 ansible_user=ubuntu

[workers]
node_b ansible_host=34.47.207.162 ansible_user=ubuntu

[cluster:children]
managers
workers

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
